export const LOG_USER = 'LOG_USER'
export const SESSION_USER = 'SESSION_USER'
export const REG_USER = 'REG_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOG_USER_ERROR = 'LOG_USER_ERROR'
